#!/usr/bin/env python3
"""Normalises a balloon STL for the arena and extracts its profile.

Input: an upright balloon mesh (axis along +z, neck at the bottom), any
units, any offset (e.g. the repository's balloon.stl).
Output:
  <out>/meshes/balloon_unit.stl  binary STL, UNIT DIAMETER (max width 1),
                                 axis = z, origin = centre of the bounding
                                 box (so a model pose = balloon centre)
  <out>/profile.yaml             surface-of-revolution profile of the same
                                 normalised mesh: [[r, z], ...] from bottom
                                 to top, r = max radial extent of the
                                 vertices in each z slice (unit diameter)

The arena scales both by the configured diameter. The profile is what
touch detection uses (distance from the drone to the balloon surface in the
meridian plane), so the popping geometry follows the actual mesh, not a
sphere.

Usage: prepare_balloon_mesh.py <balloon.stl> <out_dir> [--slices N]
"""

import argparse
import os
import struct

import numpy as np

TRIANGLE = np.dtype([('normal', '<3f4'), ('v', '<9f4'), ('attr', '<u2')])


def read_stl(path):
    data = open(path, 'rb').read()
    count = struct.unpack('<I', data[80:84])[0]
    if 84 + count * 50 == len(data):
        tris = np.frombuffer(data[84:84 + count * 50], dtype=TRIANGLE)
        return tris['v'].reshape(-1, 3, 3).astype(float)
    import re  # ASCII STL
    v = np.array(re.findall(
        rb'vertex\s+([-\d.eE+]+)\s+([-\d.eE+]+)\s+([-\d.eE+]+)', data), dtype=float)
    return v.reshape(-1, 3, 3)


def write_stl(path, tris):
    out = np.zeros(len(tris), dtype=TRIANGLE)
    normals = np.cross(tris[:, 1] - tris[:, 0], tris[:, 2] - tris[:, 0])
    norm = np.linalg.norm(normals, axis=1, keepdims=True)
    out['normal'] = np.divide(normals, norm, out=np.zeros_like(normals), where=norm > 0)
    out['v'] = tris.reshape(-1, 9)
    with open(path, 'wb') as stream:
        header = b'AVATIC balloon, unit diameter, origin at bbox centre'
        stream.write(header.ljust(80, b' '))
        stream.write(struct.pack('<I', len(tris)))
        stream.write(out.tobytes())


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument('stl')
    parser.add_argument('out_dir')
    parser.add_argument('--slices', type=int, default=48)
    args = parser.parse_args()

    tris = read_stl(args.stl)
    v = tris.reshape(-1, 3)
    lo, hi = v.min(0), v.max(0)
    centre = (lo + hi) / 2.0
    width = max(hi[0] - lo[0], hi[1] - lo[1])
    unit = (tris - centre) / width
    uv = unit.reshape(-1, 3)
    radial = np.linalg.norm(uv[:, :2], axis=1)

    z = uv[:, 2]
    edges = np.linspace(z.min(), z.max(), args.slices + 1)
    profile = []
    for a, b in zip(edges[:-1], edges[1:]):
        m = (z >= a) & (z <= b)
        if np.any(m):
            profile.append((float(radial[m].max()), float((a + b) / 2.0)))
    profile = [(profile[0][0], float(z.min()))] + profile + \
        [(profile[-1][0], float(z.max()))]

    os.makedirs(os.path.join(args.out_dir, 'meshes'), exist_ok=True)
    write_stl(os.path.join(args.out_dir, 'meshes', 'balloon_unit.stl'), unit)
    with open(os.path.join(args.out_dir, 'profile.yaml'), 'w', encoding='utf-8') as out:
        out.write('# Generated by tools/prepare_balloon_mesh.py from '
                  f'{os.path.basename(args.stl)}; do not edit.\n')
        out.write(f'# source bounding box {np.round(hi - lo, 4).tolist()} (source units),'
                  f' normalised to unit diameter.\n')
        out.write('# [r, z] of the balloon surface, bottom (neck) to top.\n')
        out.write('profile_unit_diameter:\n')
        for r, zz in profile:
            out.write(f'  - [{r:.5f}, {zz:.5f}]\n')
    print(f'{len(unit)} triangles; unit height {z.max() - z.min():.3f}, '
          f'max radius {radial.max():.3f}; {len(profile)} profile points')


if __name__ == '__main__':
    main()
