"""Launch the Pluto X simulation flown by the LEGACY kwad.cpp stack.

Kept for the legacy validation scripts (validate_legacy_sim.sh,
check_dynamics.sh). For the MagisV2 firmware and outer-loop controllers use
sim.launch.py.

Starts:
  * Gazebo Sim with the given world (GUI optional)
  * the Pluto X model, generated by xacro from the vehicle YAML
  * ros_gz_bridge (clock, IMU, battery, ground-truth odometry)

The vehicle flies the mode set in the config (pilot.initial_mode); there is
no pilot input device.

Arguments:
  config_file   vehicle/controller YAML (default: pluto_x_core
                pluto_x_estimated.yaml; legacy_kwad.yaml = original kwad.cpp)
  world         world SDF (default: pluto_x_gazebo legacy_flat.sdf)
  headless      true: server only, no GUI
  paused        true: start paused (used by legacy_flight_check.py)
  spawn_yaw     initial ENU yaw [rad]. Default 0 faces +x, the direction
                Gazebo's default camera looks. The controller holds the
                starting heading.

Example:
  ros2 launch pluto_x_bringup legacy_sim.launch.py
"""

import os

import xacro
import yaml
from ament_index_python.packages import get_package_share_directory
from launch import LaunchDescription
from launch.actions import (DeclareLaunchArgument, IncludeLaunchDescription,
                            OpaqueFunction)
from launch.launch_description_sources import PythonLaunchDescriptionSource
from launch.substitutions import LaunchConfiguration
from launch_ros.actions import Node


def _share(package: str, *parts: str) -> str:
    return os.path.join(get_package_share_directory(package), *parts)


def _launch_setup(context):
    config_file = os.path.abspath(
        LaunchConfiguration('config_file').perform(context))
    world = LaunchConfiguration('world').perform(context)
    headless = LaunchConfiguration('headless').perform(context).lower() == 'true'
    spawn_yaw = float(LaunchConfiguration('spawn_yaw').perform(context))
    paused = LaunchConfiguration('paused').perform(context).lower() == 'true'

    if not os.path.isfile(config_file):
        raise RuntimeError(f'config_file not found: {config_file}')
    with open(config_file, 'r', encoding='utf-8') as stream:
        spawn_height_m = float(
            yaml.safe_load(stream)['gazebo_model']['spawn_height_m'])

    model_sdf = xacro.process_file(
        _share('pluto_x_gazebo', 'models', 'pluto_x', 'model.sdf.xacro'),
        mappings={'config_file': config_file,
                  'flight_controller': 'legacy'}).toxml()

    gz_args = (f'{"" if paused else "-r "}{"-s " if headless else ""}'
               f'-v 3 {world}')
    gazebo = IncludeLaunchDescription(
        PythonLaunchDescriptionSource(
            _share('ros_gz_sim', 'launch', 'gz_sim.launch.py')),
        launch_arguments={'gz_args': gz_args,
                          'on_exit_shutdown': 'true'}.items())

    spawn = Node(
        package='ros_gz_sim', executable='create', output='screen',
        arguments=['-string', model_sdf, '-name', 'pluto_x',
                   '-x', '0', '-y', '0', '-z', str(spawn_height_m),
                   '-Y', str(spawn_yaw)])

    bridge = Node(
        package='ros_gz_bridge', executable='parameter_bridge', output='screen',
        parameters=[{'config_file': _share('pluto_x_bringup', 'config',
                                           'bridge.yaml'),
                     'use_sim_time': True}])
    return [gazebo, spawn, bridge]


def generate_launch_description():
    return LaunchDescription([
        DeclareLaunchArgument(
            'config_file',
            default_value=_share('pluto_x_core', 'config',
                                 'pluto_x_estimated.yaml')),
        DeclareLaunchArgument(
            'world',
            default_value=_share('pluto_x_gazebo', 'worlds', 'legacy_flat.sdf')),
        DeclareLaunchArgument('headless', default_value='false'),
        DeclareLaunchArgument('paused', default_value='false'),
        DeclareLaunchArgument('spawn_yaw', default_value='0.0'),
        OpaqueFunction(function=_launch_setup),
    ])
